service: table-school-zone

provider:
  name: aws
  region: ${opt:region, 'ap-northeast-1'}
  stage: ${opt:stage, 'dev'}

# AWS CloudFormation templates
resources:
  Resources:
    zone:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "OrgID"
            AttributeType: "S"
          -
            AttributeName: "ZoneID"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "OrgID"
            KeyType: "HASH"
          -
            AttributeName: "ZoneID"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: "1"
          WriteCapacityUnits: "1"
        TableName: { "Fn::Join" : ["", ["${self:service}", "-zone" ] ]  }

    position:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "ZoneID"
            AttributeType: "S"
          -
            AttributeName: "positionID"
            AttributeType: "S"
          -
            AttributeName: "positionStatus"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "ZoneID"
            KeyType: "HASH"
          -
            AttributeName: "positionID"
            KeyType: "RANGE"
        LocalSecondaryIndexes:
          -
            IndexName: SteatStatus
            KeySchema:
              -
                AttributeName: "ZoneID"
                KeyType: "HASH"
              -
                AttributeName: "positionStatus"
                KeyType: "RANGE"
            Projection:
              ProjectionType: "ALL"
        ProvisionedThroughput:
          ReadCapacityUnits: "1"
          WriteCapacityUnits: "1"
        TableName: { "Fn::Join" : ["", ["${self:service}", "-position" ] ]  }



    zoneTemplate:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "OrgID"
            AttributeType: "S"
          -
            AttributeName: "ZoneTemplateID"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "OrgID"
            KeyType: "HASH"
          -
            AttributeName: "ZoneTemplateID"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: "1"
          WriteCapacityUnits: "1"
        TableName: { "Fn::Join" : ["", ["${self:service}", "-zone-template" ] ]  }
