# Copyright (c) 1999-2018 Logitech, Inc.  All Rights Reserved
#
# This program is a trade secret of LOGITECH, and it is not to
# be reproduced, published, disclosed to others, copied,
# adapted, distributed or displayed without the prior
# authorization of LOGITECH.
#
# Licensee agrees to attach or embedded this notice on all copies
# of the program, including partial copies or modified versions
# thereof.
#
# -------------------------------------------------------------
# DESCRIPTION
# -------------------------------------------------------------
# User table for storage user data including UserId, Company,
# Policy, todo
# DeviceOwnerID used as an index to query the user which belongs
# to the DeviceOwnerID, it could be used for user management,
# including CRUD  manipulate
#
# -------------------------------------------------------------
# AUTHOR
# -------------------------------------------------------------
# Cenxui Lin (clin9@logitech.com)
# -------------------------------------------------------------
# DATE CREATED
# -------------------------------------------------------------
# 16 July 2018


service: school-user

provider:
  name: aws
  region: ${opt:region, 'ap-northeast-1'}
  stage: ${opt:stage, 'dev'}

# AWS CloudFormation templates
resources:
  Resources:
    UserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: {Fn::Join : ["", ["${self:service}", "-", "${self:provider.stage}"]]}
        AdminCreateUserConfig:
          AllowAdminCreateUserOnly: true
        AutoVerifiedAttributes:
          - email
        UsernameAttributes:
          - email
        Schema:
          - Name: email
            Required: true
          - Name: preferred_username
            Required: true
            Mutable: true
          - Name: org
            AttributeDataType: String
            Mutable: true
          - Name: role
            AttributeDataType: String
            Mutable: true
          - Name: dept
            AttributeDataType: String
            Mutable: true

    UserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: School
        GenerateSecret: false
        UserPoolId:
          Ref: UserPool
        ExplicitAuthFlows: [USER_PASSWORD_AUTH]

Outputs:
  UserPoolId:
    Description: Cognito user pool ID
    Value:
      Ref: UserPool
  ClientId:
    Description: Cognito user pool client ID for web app
    Value:
      Ref: UserPoolClient