service: table-school-class

provider:
  name: aws
  region: ${opt:region, 'ap-northeast-1'}
  stage: ${opt:stage, 'dev'}

# AWS CloudFormation templates
resources:
  Resources:
    device:
      Type: "AWS::DynamoDB::Table"

      Properties:
        AttributeDefinitions:
          -
            AttributeName: "UserID"
            AttributeType: "S"
          -
            AttributeName: "DeviceOwnerID"
            AttributeType: "S"
          -
            AttributeName: "UserGroup"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "UserID"
            KeyType: "HASH"

        ProvisionedThroughput:
          ReadCapacityUnits: "1"
          WriteCapacityUnits: "1"
        TableName: { "Fn::Join" : ["", ["${self:service}", "-class" ] ]  }

        GlobalSecondaryIndexes:
          -
            IndexName: "DeviceOwnerID"
            KeySchema:
            -
              AttributeName: "DeviceOwnerID"
              KeyType: "HASH"
            -
              AttributeName: "UserGroup"
              KeyType: "RANGE"

            Projection:
              ProjectionType: "ALL"
            ProvisionedThroughput:
              ReadCapacityUnits: "1"
              WriteCapacityUnits: "1"

