# Copyright (c) 1999-2018 Logitech, Inc.  All Rights Reserved
#
# This program is a trade secret of LOGITECH, and it is not to
# be reproduced, published, disclosed to others, copied,
# adapted, distributed or displayed without the prior
# authorization of LOGITECH.
#
# Licensee agrees to attach or embedded this notice on all copies
# of the program, including partial copies or modified versions
# thereof.
#
# -------------------------------------------------------------
# DESCRIPTION
# -------------------------------------------------------------
# User table for storage org data including UserId, Company,
# Policy, todo
# DeviceOwnerID used as an index to query the org which belongs
# to the DeviceOwnerID, it could be used for org management,
# including CRUD  manipulate
#
# -------------------------------------------------------------
# AUTHOR
# -------------------------------------------------------------
# Cenxui Lin (clin9@logitech.com)
# -------------------------------------------------------------
# DATE CREATED
# -------------------------------------------------------------
# 16 July 2018


service: table-school-org

provider:
  name: aws
  region: ${opt:region, 'ap-northeast-1'}
  stage: ${opt:stage, 'dev'}

# AWS CloudFormation templates
resources:
  Resources:
    device:
      Type: "AWS::DynamoDB::Table"

      Properties:
        AttributeDefinitions:
          -
            AttributeName: "OrgID"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "OrgID"
            KeyType: "HASH"

        ProvisionedThroughput:
          ReadCapacityUnits: "1"
          WriteCapacityUnits: "1"
        TableName: { "Fn::Join" : ["", ["${self:service}", "-org" ] ]  }