service: table-school-org

provider:
  name: aws
  region: ${opt:region, 'ap-northeast-1'}
  stage: ${opt:stage, 'dev'}

# AWS CloudFormation templates
resources:
  Resources:
    device:
      Type: "AWS::DynamoDB::Table"

      Properties:
        AttributeDefinitions:
          -
            AttributeName: "OrgID"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "OrgID"
            KeyType: "HASH"

        ProvisionedThroughput:
          ReadCapacityUnits: "1"
          WriteCapacityUnits: "1"
        TableName: { "Fn::Join" : ["", ["${self:service}", "-org" ] ]  }