# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: api-user # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"
frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  region: ${opt:region, 'ap-northeast-1'}
  stage: ${opt:stage, 'dev'}
  cognitoService: cognito-user
  dns: ${opt:dns, 'vclogitech.com'} # please buy a domain name
  cArn: ${opt:cArn, 'arn:aws:acm:us-east-1:895233118661:certificate/fa1490e6-5377-4eea-af15-b7a7ac11ef92'} # please buy a domain name
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:*
      Resource: { "Fn::Join" : ["", ["arn:aws:dynamodb:","${self:provider.region}", ":*:*" ] ]  }

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  userList:
    handler: bin/userList
    events:
      - http:
          path: user
          method: get
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer
  userGet:
    handler: bin/userGet
    events:
      - http:
          path: user/{userid}
          method: get
          cors: true
  userPut:
    handler: bin/userPut
    events:
      - http:
          path: user
          method: put
          cors: true
  userPost:
    handler: bin/userPost
    events:
      - http:
          path: user
          method: post
          cors: true
  userDelete:
    handler: bin/userDelete
    events:
      - http:
          path: user/{userid}
          method: delete
          cors: true
  groupList:
    handler: bin/groupList
    events:
      - http:
          path: group
          method: get
          cors: true
  groupGet:
    handler: bin/groupGet
    events:
      - http:
          path: group/{groupid}
          method: get
          cors: true
  groupPut:
    handler: bin/groupPut
    events:
      - http:
          path: group
          method: put
          cors: true
  groupPost:
    handler: bin/groupPost
    events:
      - http:
          path: group
          method: post
          cors: true
  groupDelete:
    handler: bin/groupDelete
    events:
      - http:
          path: group/{groupid}
          method: delete
          cors: true
resources:
  Resources:

    #
    # API Gateway Authorizer
    #

    ApiGatewayAuthorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        Name: CognitoUserPool
        Type: COGNITO_USER_POOLS
        IdentitySource: method.request.header.Authorization
        RestApiId:
          Ref: ApiGatewayRestApi
        ProviderARNs: [{'Fn::ImportValue': {Fn::Join: ["", ["${self:provider.cognitoService}","-","${self:provider.stage}", "-UserPoolArn" ] ]}}]

    GatewayResponseDefault4XX:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: ApiGatewayRestApi
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,Authorization'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,OPTIONS,PUT,POST,DELETE'"

    ApiGatewayBasePathMapping:
      Type: AWS::ApiGateway::BasePathMapping
      Properties:
       DomainName:
        Ref: ApiGatewayDomainName
       RestApiId:
        Ref: ApiGatewayRestApi
       Stage: ${self:provider.stage}

    ApiGatewayDomainName:
      Type: AWS::ApiGateway::DomainName
      Properties:
        CertificateArn: ${self:provider.cArn}
        DomainName: ${self:service}.${self:provider.region}.${self:provider.dns}

    #
    # Route53
    #

    DnsRecordSet:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneName: ${self:provider.dns}.
        Name: ${self:service}.${self:provider.region}.${self:provider.dns}
        Type: A
        AliasTarget:
          HostedZoneId:
            Fn::GetAtt: [ ApiGatewayDomainName, DistributionHostedZoneId ]
          DNSName:
            Fn::GetAtt: [ ApiGatewayDomainName, DistributionDomainName ]

  Outputs:
    ServiceEndpointAlias:
      Value: {Fn::Join: ['', [https://, Ref: DnsRecordSet]]}
      Export:
        {Name: {Fn::Join: ['-', [Ref: AWS::StackName, ServiceEndpoint]]}}

